-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        blur = {
            xray = true,
        },
        rounding = 10,
        rounding_power = 5.0,
    },
    general = {
        allow_tearing = true,
        col = {
            active_border = {
                colors = {"rgba(dc8addff)", "rgba(9141acff)"},
                angle = 54,
            },
        },
        resize_on_border = true,
    },
    master = {
        mfact = 0.15,
    },
    misc = {
        vrr = 2,
    },
})

-- Animations
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 1.0,
    bezier = "default",
})

-- Monitors
hl.monitor({
    output = "DP-2",
    disabled = true,
})
hl.monitor({
    output = "DP-3",
    disabled = true,
})
hl.monitor({
    output = "eDP-1",
    disabled = false,
    mode = "preferred",
    position = "auto",
    scale = 1,
})

-- Keybinds
hl.unbind("SUPER + Q")
hl.bind("SUPER + Q", hl.dsp.exec_cmd("kitty"))
